/* Blog posts — written in Micah's voice. [EDIT] freely; keep the disclaimer line. */
export const POSTS = [
  {
    slug: 'start-lifting-when-the-gym-scares-you',
    image: '/images/blog/gym-anxiety.jpg',
    title: 'How to start lifting weights when the gym scares you',
    date: '2026-07-28',
    minutes: 5,
    excerpt: 'Gym anxiety is the #1 thing stopping beginners — not motivation, not knowledge. Here is the exact playbook I give new clients for their first four weeks.',
    body: [
      { p: "Almost every client I've coached said the same thing before we started: \"I want to lift, but the gym intimidates me.\" If that's you, you're not broken — you're normal. Walking into a room full of people who seem to know what they're doing, with equipment you've never touched, is genuinely uncomfortable. The fix isn't confidence first, then the gym. It's the other way around: structure kills anxiety." },
      { h: 'Go in with a script, not a vibe' },
      { p: "Anxiety thrives on decisions. If you walk in wondering what to do, every machine becomes a question and every person becomes an audience. So we remove decisions: you go in with a written program that says exactly which exercises, in which order, with which weights, for how many sets. Your entire job is to follow the list. That's it." },
      { h: 'Start in the corners' },
      { p: "Your first two weeks don't need the squat rack at 5:30pm. Dumbbells, cable machines and fixed machines in the quieter corners build the same base while you learn the room. I program beginners' first block around equipment that's easy to access, then we graduate to barbells once the gym feels like your space." },
      { h: 'Nobody is watching (really)' },
      { p: "The regulars you're worried about? They're on their fourth set thinking about their own training. In years of coaching I've never had a client report someone mocking them. The story in your head is the anxiety talking — and it fades fast once you've done ten sessions." },
      { h: 'The 4-week confidence plan' },
      { p: "Week 1: two short sessions, machines and dumbbells only, off-peak if you can. Week 2: same sessions, add one new exercise. Week 3: introduce the barbell with just the bar, filmed so we can check technique. Week 4: full program, any time of day. Every client who's followed this tells me the same thing at the end: \"I can't believe I was scared of this.\"" },
      { p: "If you want the accountability version of this — a program built for you, form checks in your DMs, and a weekly call to keep you honest — that's exactly what my 1:1 coaching is. Book a free intro call and we'll talk about where you're starting from." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'how-fast-do-beginners-build-muscle',
    image: '/images/blog/muscle-timeline.jpg',
    title: 'How fast do beginners actually build muscle? A realistic 12-week timeline',
    date: '2026-07-14',
    minutes: 6,
    excerpt: "Forget the transformation ads. Here's what actually happens in your first 12 weeks of proper resistance training — week by week, no hype.",
    body: [
      { p: "The fitness industry sells 8-week miracles. I'd rather tell you the truth, because the truth is still genuinely exciting: beginners progress faster than anyone else in the gym. Here's the honest timeline I see over and over with new clients." },
      { h: 'Weeks 1–3: your nervous system wakes up' },
      { p: "Strength jumps quickly at the start — sometimes 5–10% on a lift per week. Almost none of that is new muscle. It's your nervous system learning to coordinate the muscle you already have. Don't be discouraged that the mirror hasn't changed yet; the wiring comes before the hardware." },
      { h: 'Weeks 3–6: the habit locks in' },
      { p: "This is where most people quit — the novelty has worn off and visible change is only starting. It's also exactly where a coach earns their keep. Sessions feel natural, weights keep climbing in small jumps, sleep and appetite usually improve. Around week 5–6, clothes start fitting differently before the scale moves much." },
      { h: 'Weeks 6–12: visible change' },
      { p: "With consistent training and adequate protein, most beginners can build roughly 0.5–1kg of muscle in their first 12 weeks — more for some, less for others, and it varies hugely with sleep, food and genetics. Shoulders and arms usually show first, then the bigger patterns: you look 'trained' rather than just slimmer." },
      { h: 'What actually moves the needle' },
      { p: "Three things, in order: showing up (2–4 sessions a week, every week), progressive overload (small trackable increases — this is why we log everything), and protein (roughly 1.6–2.2g per kg of bodyweight daily). Everything else — supplements, fancy splits, the perfect exercise — is rounding error at this stage." },
      { h: 'The mistake that resets the clock' },
      { p: "Program-hopping. Changing plans every two weeks because something on social media looked better is the fastest way to stay a beginner forever. Pick a sensible program, run it for a full block, then adjust based on data. That's exactly how I run coaching blocks with clients." },
      { p: "General information only — not medical advice. If you have a health condition or injury, talk to your GP or physio before starting a new training program." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'three-day-beginner-split-that-sticks',
    image: '/images/blog/three-day-split.jpg',
    title: 'The 3-day beginner split that actually sticks',
    date: '2026-06-30',
    minutes: 5,
    excerpt: "You don't need a 6-day bro split. Three full-body sessions a week builds more muscle than the perfect program you quit in February.",
    body: [
      { p: "Ask a beginner to train six days a week and you'll get three great weeks followed by silence. Ask them to train three days and you'll still be getting check-in messages in December. Adherence beats optimisation — every single time." },
      { h: 'Why full-body, three days' },
      { p: "As a beginner you don't need much volume to grow — you need frequency and practice. Hitting each movement pattern three times a week means three chances to practise technique, three chances to add a little weight, and no wasted sessions if life eats one of your gym days." },
      { h: 'The template' },
      { p: "Each session: one squat pattern (goblet squat, leg press), one hinge (Romanian deadlift, hip thrust), one push (dumbbell bench, machine press), one pull (lat pulldown, seated row), and one or two accessories you actually enjoy — arms, abs, whatever keeps you coming back. 45–60 minutes, done." },
      { h: 'How to progress it' },
      { p: "The simplest rule in strength training: when you hit the top of the rep range on every set with good form, add the smallest jump available next session. 2.5kg on machines, 1–2kg on dumbbells. Log every session — what gets measured gets built." },
      { h: 'When to change it' },
      { p: "Not after two weeks. Run it for 8–12 weeks, then adjust based on what the log says. If lifts are still climbing, you don't need a new program — you need more weeks of this one. When progress genuinely stalls, that's when block two gets built around your data." },
      { p: "Want this done for you — with the exercises picked for your gym, your schedule and your goals, plus someone checking your form videos? That's my 1:1 coaching. The intro call is free." },
      { p: "General information only — not medical advice. See your GP before starting a new program if you have any health concerns." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'fat-loss-vs-toning-truth',
    image: '/images/blog/fat-loss-toning.jpg',
    title: "Fat loss vs 'toning up': what's actually happening",
    date: '2026-06-16',
    minutes: 5,
    excerpt: "'I don't want to get bulky, I just want to tone.' Let's clear up the most common confusion in fitness — and why lifting is exactly how you get the look you want.",
    body: [
      { p: "\"I don't want to get big — I just want to tone up.\" I hear this in almost every intro call, usually from someone worried that lifting weights will turn them into a bodybuilder by accident. Here's the reality: 'toned' is just muscle with less fat over it. There is no separate 'toning' exercise. There's building muscle, and there's losing fat, and the look you're after is both." },
      { h: "You can't get bulky by accident" },
      { p: "Building serious size takes years of dedicated training, eating in a surplus, and usually genetics on your side. Nobody wakes up accidentally huge after twelve weeks of goblet squats. What actually happens in your first months of lifting: muscles get a little firmer and rounder, posture improves, and as fat comes off the shape underneath shows through. That IS the toned look." },
      { h: 'Why cardio-only backfires' },
      { p: "Hours of cardio in a big calorie deficit strips muscle along with fat. You end up lighter but softer — 'skinny fat' — and your metabolism takes a hit because you've lost the most metabolically expensive tissue you had. Resistance training while losing fat is what protects the muscle, so what's left behind is shape, not just less of you." },
      { h: 'The actual recipe' },
      { p: "Lift 2–4 times a week with progressive overload. Eat a modest calorie deficit — 300–500 below maintenance, not a starvation diet. Keep protein around 1.6–2.2g per kg of bodyweight. Walk more. Sleep 7+. Run that for 12 weeks and you'll understand why I don't program 'toning circuits' for anyone." },
      { h: 'What the scale won\'t tell you' },
      { p: "When you build muscle while losing fat, the scale can barely move while your body visibly changes. This is why my clients track waist measurements, progress photos and gym numbers — not just weight. More than one client has stayed within 2kg on the scale while dropping two clothing sizes." },
      { p: "General information only — not medical or dietary advice. For personalised nutrition guidance, especially with a medical condition, see a registered dietitian or your GP." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'protein-for-beginners',
    image: '/images/blog/protein-for-beginners.jpg',
    title: 'Protein for beginners: how much, when, and does it actually matter?',
    date: '2026-06-08',
    minutes: 6,
    excerpt: "Protein is the one nutrition lever that genuinely matters for beginners — but the industry has buried it under powders, timing myths and fear. Here are the numbers that actually count.",
    body: [
      { p: "If you're new to lifting, nutrition advice online is a firehose of contradictions. So let me simplify it: after total calories, protein is the only nutrition variable I ask beginners to actively track. Get it roughly right and you've captured most of the benefit. Obsess over the rest later — or never." },
      { h: 'How much do you actually need?' },
      { p: "The research on this is unusually consistent: for people doing resistance training, somewhere around 1.6–2.2g of protein per kilogram of bodyweight per day is where the benefits plateau. For a 75kg person, that's roughly 120–165g a day. More than that isn't dangerous for healthy people, but it isn't buying you extra muscle either — it's just expensive." },
      { p: "And here's the part nobody sells: you don't need to hit it perfectly. If you're currently eating 60g a day and you get to 110g, you've captured most of the win. Precision matters far less than the overall trend." },
      { h: 'Does timing matter?' },
      { p: "Far less than the supplement industry wants you to believe. The old 'anabolic window' — the idea that you must slam a shake within 30 minutes of training or the session is wasted — doesn't hold up. What the evidence supports is simpler: spread your protein across the day in 3–5 feeds of roughly 25–40g each, because your body uses it better in decent doses than in one giant dinner. If one of those feeds happens to land near your workout, great. If not, your muscles will cope." },
      { h: 'Do you need protein powder?' },
      { p: "Need? No. It's not magic — it's just food in powder form, and whole foods like chicken, eggs, fish, dairy, tofu and legumes should do most of the work. But is a scoop of whey (or a plant blend) a cheap, convenient way to close a 30g gap on a busy day? Absolutely. I'd rather you think of powder as a convenience tool, like frozen vegetables, than as a supplement with special powers." },
      { h: 'The practical version' },
      { p: "Here's what I actually ask new clients to do: build each main meal around a palm-to-two-palm-sized portion of a protein source, add a protein-focused snack (Greek yoghurt, cottage cheese, a shake) if the day is falling short, and track intake loosely for two weeks just to calibrate your eye. After that, most people can hold the habit without weighing anything. Boring? Yes. Effective? Also yes." },
      { p: "If you want the guesswork removed entirely — protein and calorie targets set for your body and goal, adjusted as your training progresses, with someone checking in weekly — that's part of what my 1:1 online coaching covers. Book a free intro call and we'll sort it out together." },
      { p: "General information only — not medical or dietary advice. If you have kidney issues or any medical condition affecting diet, talk to your GP or a registered dietitian before changing your protein intake." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'gym-bag-essentials',
    image: '/images/blog/gym-bag-essentials.jpg',
    title: "The beginner's gym bag: what you actually need (and what's a waste)",
    date: '2026-05-28',
    minutes: 4,
    excerpt: "You don't need $400 of gear to start lifting. Here's the short list I give every new client — and the stuff you can happily skip for your first year.",
    body: [
      { p: "One of the sneakier ways people delay starting the gym is gear shopping. It feels productive — researching shoes, comparing belts, filling a cart with accessories — but it's usually just procrastination with a receipt. Here's the honest list of what a beginner actually needs, from someone who watches beginners train every week." },
      { h: 'The genuine essentials' },
      { p: "A water bottle, because dehydrated training feels worse than it needs to. A sweat towel, because gym etiquette matters and shared benches are shared benches. Flat, stable shoes — and here's the good news: you probably already own them. Court shoes, Vans-style flats, or even training barefoot-style shoes all beat squishy running shoes for lifting, because a stable base matters when there's weight on your back. Your phone with your program and log on it. That's honestly the whole list." },
      { h: 'Genuinely useful, but not urgent' },
      { p: "Wireless earphones make sessions more enjoyable, and enjoyment drives consistency, so I'll happily call them a good investment. A small notebook if you'd rather log on paper. A resistance band for warm-ups. None of these will change your results, but they make the habit more pleasant — and the habit IS the result at this stage." },
      { h: 'What you can skip for your first year' },
      { p: "A lifting belt: useful much later for heavy barbell work, irrelevant while you're learning movements with moderate loads. Straps: your grip should be allowed to develop first. Knee sleeves, wrist wraps, lifting shoes: solve problems you don't have yet. Pre-workout: a coffee does most of the same job for a fraction of the price. BCAAs: genuinely unnecessary if you're eating enough protein — the research here is pretty damning. If in doubt, ask yourself: is this fixing a problem I've actually experienced, or one an ad told me I have?" },
      { h: 'The one upgrade worth making early' },
      { p: "If you're going to spend money on anything, spend it on things that remove friction from showing up: a bag that lives packed by the door, a gym close to your commute rather than the fancy one across town, a membership you'll actually use. The best gear purchase is the one that gets you through the door on a rainy Tuesday in July." },
      { p: "And if what's really missing from your bag is a plan — a program written for your gym and your goals, with someone keeping you accountable — that's what I do. My 1:1 online coaching starts with a free intro call, no hard sell, just a conversation about where you're at." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'sore-vs-injured',
    image: '/images/blog/sore-vs-injured.jpg',
    title: 'Sore or injured? How to tell the difference',
    date: '2026-05-19',
    minutes: 5,
    excerpt: "Every beginner hits this moment: something hurts, and you don't know if it's normal soreness or a real problem. Here's a practical framework for telling them apart.",
    body: [
      { p: "At some point in your first months of training, something will hurt and you'll stand in your kitchen wondering: is this just soreness, or have I done something? It's one of the most common questions I get from new clients, and while I can't diagnose anyone over the internet, I can give you the framework I use to decide what to do next." },
      { h: 'What normal soreness feels like' },
      { p: "Delayed onset muscle soreness — DOMS — is the classic post-training ache. It shows up 24–48 hours after a session (often worse on day two), lives in the belly of the muscle rather than a joint, feels dull and stiff rather than sharp, affects both sides if you trained both sides, and eases once you warm up and move. It's most dramatic when an exercise is new, and it fades over the following weeks as your body adapts. Heavy DOMS is not a badge of a good workout, by the way — it's mostly a sign of novelty." },
      { h: 'The warning signs that suggest something more' },
      { p: "Pain that's sharp or stabbing rather than dull. Pain located in or around a joint rather than in muscle. Pain that appeared suddenly during a rep — especially with a pop, click or tearing sensation. One-sided pain after a symmetrical exercise. Swelling, bruising, or a joint that feels unstable or won't take weight. Pain that gets worse as you warm up instead of better, or that's still just as bad after 5–7 days. None of these automatically mean disaster, but they all mean stop pushing and get it looked at." },
      { h: 'The traffic light system I use with clients' },
      { p: "Green: dull, symmetrical muscle soreness that eases with movement — train as planned, maybe go slightly lighter. Orange: discomfort around 3–4 out of 10 that doesn't sharpen during the session and settles within a day — modify the session, reduce the load or swap the exercise, and monitor. Red: anything sharp, joint-based, swelling, or pain above 4–5 that changes how you move — stop that exercise, don't test it repeatedly, and if it persists more than a few days, book a physio. In New Zealand you can see a physio directly without a GP referral, and ACC often covers a chunk of injury-related treatment." },
      { h: "Why 'pushing through' is a false economy" },
      { p: "Missing one week of training costs you almost nothing — beginners regain any lost ground within days. Turning a niggle into a proper injury by repeatedly loading it can cost you months. When clients flag pain to me, we adjust the program the same day: there is almost always a way to keep training productively around an issue while it settles. The gym rewards patience far more than bravery." },
      { p: "This is exactly the kind of judgement call that's easier with a coach in your corner — someone who sees your videos, knows your history, and tells you honestly when to push and when to back off. If you want that, book a free intro call." },
      { p: "General information only — not medical advice. If you're in significant pain, or something feels wrong, see a physio or your GP. Seek urgent care for severe pain, numbness, or an injury that won't bear weight." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'cardio-and-lifting',
    image: '/images/blog/cardio-and-lifting.jpg',
    title: 'Cardio and lifting: how to combine them without killing your gains',
    date: '2026-05-08',
    minutes: 6,
    excerpt: "No, cardio won't melt your muscle away. Here's how to fit both into a week so they help each other instead of fighting.",
    body: [
      { p: "Somewhere along the way, lifters got taught to fear cardio like it dissolves muscle on contact. Meanwhile, runners got taught lifting would make them slow and heavy. Both camps are wrong, and beginners caught in the middle end up doing neither properly. Let's fix that." },
      { h: "The 'interference effect' — real, but wildly overblown" },
      { p: "The concern has a real scientific basis: research on concurrent training shows that large amounts of endurance work can blunt some strength and muscle adaptations. But look closer at those studies and the interference mostly shows up with high volumes of intense cardio stacked directly against lifting. For someone lifting three days a week and doing a couple of moderate cardio sessions? The effect ranges from small to basically undetectable. You are not an elite athlete juggling twelve sessions a week — the rules that apply to them barely apply to you." },
      { h: 'What cardio actually does for your lifting' },
      { p: "A base level of aerobic fitness means you recover faster between sets, handle more volume without gasping, and bounce back better between sessions. It's also, not to bury the lede, extremely good for your heart, your blood pressure, your sleep and your long-term health — which is presumably part of why you're training at all. I'd rather build strong people who can also climb a hill without stopping." },
      { h: 'How to structure a week' },
      { p: "The simple version for a beginner lifting three days a week: add 2–3 cardio sessions of 20–40 minutes at an easy-to-moderate pace — you should be able to hold a conversation. Walking counts. Cycling, swimming and rowing are great low-impact options. If you can, put cardio on non-lifting days. If you have to combine them, lift first and do cardio after, because you want your freshest effort going to the skill-heavy work. And keep the hard intervals occasional while you're new — easy cardio gives you most of the health benefit with almost none of the recovery cost." },
      { h: 'Two practical rules of thumb' },
      { p: "First: prioritise by goal. If building strength and muscle is the main aim, cardio is the supporting act — keep it easy enough that it never wrecks tomorrow's leg session. If your goal is general health and fat loss, the mix matters less than the consistency of both. Second: watch the sequencing around lower body days. A brutal hill run the day before heavy squats will show up in your log. Shuffle the week so your legs get to be fresh for the work that needs them." },
      { h: "When cardio does become a problem" },
      { p: "If your lifts have stalled, you're constantly tired, and you're doing an hour of hard cardio five days a week while trying to build muscle in a calorie deficit — the cardio isn't the villain, the total picture is. Recovery is a budget. Spend it deliberately." },
      { p: "If you'd like a week designed for you — lifting, cardio and recovery balanced around your actual schedule and goal — that's exactly what I build for my 1:1 coaching clients. The intro call is free." },
      { p: "General information only — not medical advice. If you have a heart condition or other health concerns, check in with your GP before adding new cardio or lifting work." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'sleep-and-muscle',
    image: '/images/blog/sleep-and-muscle.jpg',
    title: 'Sleep: the training variable nobody logs',
    date: '2026-04-28',
    minutes: 5,
    excerpt: "You track sets, reps and protein — but the biggest recovery tool you own never makes it into the log. Here's why sleep deserves a spot in your program.",
    body: [
      { p: "If I offered you a free supplement that improved strength, sped up muscle growth, reduced injury risk, controlled appetite and made you feel like training — you'd take it. That supplement is sleep, it's already in your house, and most people treat it as the thing that gets sacrificed first when life gets full." },
      { h: 'What the research actually shows' },
      { p: "This isn't bro-science. Sleep restriction has been shown to reduce testosterone and growth hormone output, impair muscle protein synthesis, and shift the body toward losing lean mass — one well-known study found dieters who slept short lost significantly more of their weight as muscle instead of fat compared to the same people sleeping longer. Short sleep also raises perceived effort, drops next-day strength and willpower, and cranks up hunger hormones so the pantry gets louder. In athlete populations, chronic short sleep is linked with substantially higher injury rates. Almost every lever you're pulling in the gym gets partially unwound by bad sleep." },
      { h: 'How much is enough?' },
      { p: "For most adults doing regular training, 7–9 hours is the honest range. Some people genuinely thrive at 7; almost nobody thrives at 5 and a half, no matter what they've convinced themselves. The tell isn't how you feel at your desk with coffee on board — it's whether you need an alarm to drag you out of bed every single day, and whether your weekend sleep is two hours longer than your weekday sleep. That gap is debt, not preference." },
      { h: 'The basics that actually move the needle' },
      { p: "Keep your wake time roughly consistent, even on weekends — your body clock anchors to it. Cut caffeine after early afternoon; it has a long half-life and quietly shreds deep sleep even when you fall asleep fine. Make the room dark and cool. Give yourself a 30–60 minute wind-down without the doomscroll. None of this is glamorous, which is exactly why nobody sells it — there's no margin in 'go to bed'." },
      { h: 'What I do about it as a coach' },
      { p: "My client check-ins ask about sleep every single week, right alongside training and food, because it's usually the first place a stalled program points. If your lifts have flatlined and your sleep column reads six hours, we fix the sleep before we touch the program. A tired body doesn't need a cleverer training plan — it needs recovery. And on brutal weeks, we plan for it: shorter sessions, easier loads, no guilt. Training hard on four hours of sleep isn't discipline, it's just borrowing from tomorrow." },
      { p: "If you want a coach who looks at the whole picture — training, food, sleep, stress — instead of just emailing you a PDF, that's how my 1:1 online coaching works. Book a free intro call and let's talk." },
      { p: "General information only — not medical advice. If you snore heavily, wake unrefreshed every day, or suspect a sleep disorder like sleep apnoea, talk to your GP — those are treatable and worth taking seriously." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'first-gym-session',
    image: '/images/blog/first-gym-session.jpg',
    title: 'Your first gym session: exactly what to do, minute by minute',
    date: '2026-04-17',
    minutes: 6,
    excerpt: "Not a philosophy, not a pep talk — an actual minute-by-minute script for your very first session, from walking in the door to walking out.",
    body: [
      { p: "The hardest gym session of your life is the first one, and it has nothing to do with the weights. It's the not-knowing: where do I go, what do I touch, how long do I stay, when am I allowed to leave? So here's the script. Follow it literally. Total time: about 45 minutes." },
      { h: 'Minutes 0–5: walk in, find your bearings' },
      { p: "Scan your card, and if it's your first visit, tell the front desk exactly that — most gyms will happily give you a two-minute tour of where things are. Find three things: the dumbbell area, the machines, and the water fountain. Put your stuff in a locker. You now know the room. That's the whole job of the first five minutes." },
      { h: 'Minutes 5–13: warm up' },
      { p: "Hop on any cardio machine — bike is the least coordination-demanding — and go at an easy pace for 5–8 minutes until you feel warm. This isn't a workout; it's a buffer that raises your temperature and, just as importantly, gives your nerves time to settle while you do something you can't get wrong." },
      { h: 'Minutes 13–43: the workout — five exercises, machines only' },
      { p: "Today is deliberately machine-based, because machines guide the movement path while you learn. Do 2 sets of 10–12 on each: leg press, chest press, lat pulldown (or seated row), seated shoulder press, and leg curl. Rest about 90 seconds between sets. Pick a weight that feels genuinely easy — you should finish every set knowing you had 4–5 more reps in you. Adjust the seat before every machine (there's usually a diagram on the machine itself showing how). Log the weight you used for each exercise in your phone." },
      { h: "Why so easy? Because today isn't about the muscles" },
      { p: "The purpose of session one is not stimulus — it's evidence. Evidence that you can walk in, do a session and walk out. Going too hard today buys you nothing except crippling soreness that makes session two less likely, and session two is the only thing that matters right now. The training effect comes from the weeks, not the day." },
      { h: 'Minutes 43–45: finish and book the rematch' },
      { p: "Wipe down anything you sweated on, grab your stuff, and before you leave the car park, put your next session in your calendar — ideally within three days. A first session without a booked second session is just a visit. Two sessions is the start of a pattern." },
      { h: 'What about next time?' },
      { p: "Session two: same five exercises, add a third set. Session three: nudge the weights up slightly on anything that felt easy. Congratulations — you've just done progressive overload, which is the entire engine of strength training. From there, a structured beginner program takes over." },
      { p: "If you'd rather skip the guesswork entirely — a program built for your gym, form checks on your videos, and someone to answer the 'is this right?' questions in your first weeks — that's my 1:1 online coaching. The intro call is free and friendly." },
      { p: "General information only — not medical advice. If you have a health condition, injury history, or you're returning from a long layoff, check in with your GP or physio before starting." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'progressive-overload-explained',
    image: '/images/blog/progressive-overload-explained.jpg',
    title: 'Progressive overload, explained in plain English',
    date: '2026-04-07',
    minutes: 5,
    excerpt: "Strip away the jargon and strength training runs on one idea. If you understand progressive overload, you understand 90% of what makes a program work.",
    body: [
      { p: "Here's the entire principle in one sentence: to keep getting stronger, you have to gradually ask your body to do slightly more than it's currently used to. That's progressive overload. Every effective program ever written — no matter how fancy the branding — is a delivery system for that one sentence." },
      { h: 'Why your body demands it' },
      { p: "Your body is ruthlessly economical. Muscle is expensive tissue to build and maintain, so your body only keeps what the environment demands. When you lift something challenging, you send a signal: current capacity isn't enough. Your body adapts — a bit more muscle, better coordination, tougher connective tissue. But here's the catch: once you've adapted, the same weight is no longer a challenge, so the signal goes quiet. Lift the same 10kg dumbbells for a year and your body finishes adapting in a couple of months, then just... maintains. Overload is how you keep the conversation going." },
      { h: "'More' doesn't only mean more weight" },
      { p: "Adding weight is the most obvious lever, but it's one of several. You can do more reps with the same weight. More sets. Better technique through a fuller range of motion — a deeper squat at the same weight is overload. Shorter rest for the same work. Slower, more controlled reps. Early on you'll mostly ride the weight and reps levers, but knowing the others matters, because some weeks the bar won't go up and you can still progress." },
      { h: 'The double progression method — the only system a beginner needs' },
      { p: "Here's the version I give almost every new client. Take an exercise and give it a rep range, say 8–12. Start at a weight where you can do 8 clean reps. Each session, try to add a rep or two per set. When you hit 12 good reps on all sets, add the smallest jump available — 1–2kg on dumbbells, 2.5kg on machines — and drop back to 8s. Repeat for months. It's self-regulating, it's nearly impossible to get wrong, and it's why the log matters: you can't beat last session if you don't know what last session was." },
      { h: 'What it is NOT' },
      { p: "Progressive overload is not adding weight every session forever — that maths breaks within months, and chasing it with degrading form is how beginners get hurt or stuck. It's not soreness, sweat or exhaustion; a session can feel brutal and deliver zero overload, or feel controlled and deliver plenty. And it's not linear. Progress arrives in stair-steps: a few weeks of climbing, a plateau, another climb. The plateau isn't failure — it's the adaptation happening. Zoom out to the monthly view and the line points up." },
      { h: 'The honest summary' },
      { p: "Show up consistently, log everything, beat the log a little at a time, and let the boring maths compound. That's the whole game. Everything else in program design is just details around this engine." },
      { p: "If you'd like the engine managed for you — a program where the progression is planned, adjusted from your actual numbers each week — that's what my 1:1 online coaching does. Book a free intro call and we'll talk about your starting point." },
      { p: "General information only — not medical advice. Progress at a pace your body tolerates, and see a physio or your GP if pain shows up along the way." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'training-around-busy-weeks',
    image: '/images/blog/training-around-busy-weeks.jpg',
    title: 'How to keep training when life gets busy',
    date: '2026-03-27',
    minutes: 5,
    excerpt: "Busy weeks are not the exception — they're the schedule. Here's how to keep the training habit alive when work, family and life all peak at once.",
    body: [
      { p: "Every beginner plans their training for the perfect week — the one with free evenings, full nights of sleep and zero surprises. Then real life shows up: a work deadline, a sick kid, a trip, a season where everything peaks at once. The people who succeed long-term aren't the ones with calmer lives. They're the ones with a plan for the chaos." },
      { h: "The all-or-nothing trap" },
      { p: "Here's the pattern that kills more progress than any bad program: the week gets busy, the full session feels impossible, so nothing happens. Then next week feels like 'starting again', which feels heavy, so it slips too. Three weeks later the habit is gone — not because of one busy week, but because of the all-or-nothing thinking that followed it. The fix is deciding, in advance, that a reduced session always beats a skipped one." },
      { h: 'The minimum effective session' },
      { p: "You can protect most of your progress with shockingly little. Research on training reduction consistently shows that maintaining strength and muscle takes far less volume than building it — even a single decent weekly session, kept reasonably heavy, holds the line for weeks. So here's the busy-week version I give clients: 25 minutes, three or four compound exercises, 2 hard sets each. One squat or leg pattern, one push, one pull, done. It's not the program. It's the program's bodyguard." },
      { h: 'Plan the bad week before it arrives' },
      { p: "Sit down now, in a calm moment, and write your three tiers. Tier 1: the full program, for normal weeks. Tier 2: the 25-minute version above, for busy weeks. Tier 3: the absolute floor — say, one session plus two 20-minute walks — for the genuinely brutal weeks. When chaos hits, you're not making decisions with a fried brain; you're just selecting a tier. Decision-making is exactly what a stressful week doesn't have spare capacity for, so do the deciding early." },
      { h: 'Shrink the friction, not just the session' },
      { p: "Busy weeks are won on logistics. Train in the morning before the day can steal the slot. Keep a packed bag in the car. Pick the gym near work over the nicer one that adds twenty minutes of driving. If you can't get to the gym at all, a pair of dumbbells at home or even a bodyweight circuit keeps the pattern alive — the habit of showing up is worth protecting even when the stimulus is modest." },
      { h: 'One more reframe' },
      { p: "A busy season handled with Tier 2 sessions isn't a failure — it's proof you've become someone who trains, rather than someone who trains when it's convenient. Consistency isn't never missing; it's never missing twice without a plan." },
      { p: "This is honestly where online coaching shines: when your week implodes, you message me, and the plan adjusts to reality instead of guilt-tripping you from a PDF. If you want that kind of flexibility with accountability attached, book a free intro call." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'common-beginner-mistakes',
    image: '/images/blog/common-beginner-mistakes.jpg',
    title: '7 beginner gym mistakes I fix every single week',
    date: '2026-03-17',
    minutes: 6,
    excerpt: "Not the clickbait list — the actual mistakes I correct over and over as a coach, and the simple fix for each one.",
    body: [
      { p: "These aren't hypothetical mistakes from a listicle factory. These are the seven things I find myself correcting again and again with new clients — usually within the first fortnight. If you're starting out, skipping these will put you months ahead of where I usually meet people." },
      { h: '1. Program-hopping every two weeks' },
      { p: "New program, three sessions, then a video convinces you a different split is better. Repeat forever, progress never. Programs work through accumulated weeks of progression on the same movements — the log needs time to tell a story. The fix: pick any sensible beginner program and commit to 8–12 weeks before you're allowed an opinion about it." },
      { h: '2. Training to failure on everything' },
      { p: "Grinding every set to a shaking, form-collapsing rep feels productive, but it torches recovery, wrecks technique practice, and isn't necessary for growth — research shows sets taken close to failure (1–3 reps left in the tank) build muscle just as well with far less wear. The fix: end most sets when you could still do 2 more clean reps. Save true grinders for rare occasions, if ever." },
      { h: '3. Ego-loading before earning it' },
      { p: "Adding weight faster than technique can keep up, quarter-squatting what should be a full squat, bouncing the bar off the chest. The load your ego lifts and the load your muscles lift are different numbers. The fix: full range of motion, controlled reps, and only add weight when every rep at the current weight is clean. Filming a set once a week tells you the truth your mirror won't." },
      { h: '4. Skipping the log' },
      { p: "If you don't know what you lifted last session, you can't deliberately beat it — and deliberately beating it is the entire mechanism of progress. The fix takes ten seconds a set: exercise, weight, reps, in your phone. This is the single highest-return habit in training." },
      { h: '5. Random exercise order' },
      { p: "Doing arms first because the machine was free, then wondering why the big lifts feel weak. The fix: compound movements — squats, presses, rows, hinges — go first while you're fresh, because they carry the most weight, need the most skill, and drive the most progress. Accessories mop up afterwards." },
      { h: "6. Copying advanced lifters' programs" },
      { p: "The six-day program of a lifter with ten years of muscle is built for problems you don't have and recovery you can't match. Beginners thrive on the opposite: less volume, more frequency per movement, simpler exercises. The fix: three full-body sessions a week will out-build any borrowed pro split, because you'll actually recover from it and actually stick to it." },
      { h: '7. Judging the week instead of the month' },
      { p: "One flat session and beginners panic; one great session and they add 10kg to everything. Both are noise. Strength wobbles day to day with sleep, stress and food. The fix: zoom out. Judge progress on the four-week trend in your log, not on how Tuesday felt." },
      { p: "Notice the theme? None of these are fixed by trying harder — they're fixed by structure and a second set of eyes. That's the job description of a coach. If you'd like those eyes on your training from day one, my 1:1 online coaching starts with a free intro call." },
      { p: "General information only — not medical advice. If pain, not just effort, is what's limiting your training, see a physio or your GP." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'online-coaching-vs-pt',
    image: '/images/blog/online-coaching-vs-pt.jpg',
    title: 'Online coaching vs in-person PT: which is right for you?',
    date: '2026-03-05',
    minutes: 6,
    excerpt: "I coach online today, and in-person Christchurch sessions launch in September. Here's an honest guide to which format fits you — and how to use both.",
    body: [
      { p: "I'm in a useful position to answer this honestly: I coach online today, and I'm launching in-person sessions throughout Christchurch this September. Neither format is 'better' — they solve different problems, and picking the right one matters more than picking the fancy one. Here's how I help people decide on their intro call." },
      { h: 'When in-person is the right call' },
      { p: "Real-time correction is the killer feature. Standing next to you, I can adjust your squat mid-rep, catch things a camera misses, and physically demonstrate what a cue means. There's also the appointment effect: a booked session with a coach waiting is powerful accountability if you struggle to self-start. If you're brand new, nervous about the gym floor, or learning barbell lifts from zero — starting in person builds technique and confidence fastest. This is exactly why my in-person waitlist exists — if that's you, get on it before September." },
      { h: 'When online is the right call' },
      { p: "Online coaches your whole week, not just the booked hour. You get the full program in the Hevy app, form review on videos of your actual working sets, a weekly check-in covering training and recovery, and a coach in your pocket when questions come up on a Wednesday night. If your schedule is chaotic, you travel, you live outside Christchurch, or you're comfortable enough to train alone but want programming and accountability — online gives you more coaching per dollar than any other format." },
      { h: 'The honest trade-offs' },
      { p: "In person, you get supervision for the session — but the rest of your week still needs a plan (which is why even my in-person clients get the app and a full program). Online, nobody is physically there to spot you or fix a rep in real time — form checks happen on video, which works brilliantly but isn't instant. Neither drawback is fatal; they just suit different people." },
      { h: 'The answer for most beginners: start in person, go hybrid' },
      { p: "The path that works over and over: build the habit and the program online now, then add in-person sessions from September to sharpen technique — same coach, same program, no restart. Online clients get first pick of in-person times when doors open. You're not choosing forever; you're choosing where to start." },
      { h: 'How to decide in 30 seconds' },
      { p: "Start online now if: you want coaching this month, your weeks are unpredictable, or you're happy training solo with a plan and weekly accountability. Join the September in-person waitlist if: you're in Christchurch, you're new or nervous, and you want hands-on technique coaching from day one. Genuinely unsure? That's what the free intro call is for — I'll tell you straight, and it costs nothing to find out." },
      { p: "— Micah" },
    ],
  },
]
