/* Blog posts — written in Micah's voice. [EDIT] freely; keep the disclaimer line. */
export const POSTS = [
  {
    slug: 'start-lifting-when-the-gym-scares-you',
    title: 'How to start lifting weights when the gym scares you',
    date: '2026-07-28',
    minutes: 5,
    excerpt: 'Gym anxiety is the #1 thing stopping beginners — not motivation, not knowledge. Here is the exact playbook I give new clients for their first four weeks.',
    body: [
      { p: "Almost every client I've coached said the same thing before we started: \"I want to lift, but the gym intimidates me.\" If that's you, you're not broken — you're normal. Walking into a room full of people who seem to know what they're doing, with equipment you've never touched, is genuinely uncomfortable. The fix isn't confidence first, then the gym. It's the other way around: structure kills anxiety." },
      { h: 'Go in with a script, not a vibe' },
      { p: "Anxiety thrives on decisions. If you walk in wondering what to do, every machine becomes a question and every person becomes an audience. So we remove decisions: you go in with a written program that says exactly which exercises, in which order, with which weights, for how many sets. Your entire job is to follow the list. That's it." },
      { h: 'Start in the corners' },
      { p: "Your first two weeks don't need the squat rack at 5:30pm. Dumbbells, cable machines and fixed machines in the quieter corners build the same base while you learn the room. I program beginners' first block around equipment that's easy to access, then we graduate to barbells once the gym feels like your space." },
      { h: 'Nobody is watching (really)' },
      { p: "The regulars you're worried about? They're on their fourth set thinking about their own training. In years of coaching I've never had a client report someone mocking them. The story in your head is the anxiety talking — and it fades fast once you've done ten sessions." },
      { h: 'The 4-week confidence plan' },
      { p: "Week 1: two short sessions, machines and dumbbells only, off-peak if you can. Week 2: same sessions, add one new exercise. Week 3: introduce the barbell with just the bar, filmed so we can check technique. Week 4: full program, any time of day. Every client who's followed this tells me the same thing at the end: \"I can't believe I was scared of this.\"" },
      { p: "If you want the accountability version of this — a program built for you, form checks in your DMs, and a weekly call to keep you honest — that's exactly what my 1:1 coaching is. Book a free intro call and we'll talk about where you're starting from." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'how-fast-do-beginners-build-muscle',
    title: 'How fast do beginners actually build muscle? A realistic 12-week timeline',
    date: '2026-07-14',
    minutes: 6,
    excerpt: "Forget the transformation ads. Here's what actually happens in your first 12 weeks of proper resistance training — week by week, no hype.",
    body: [
      { p: "The fitness industry sells 8-week miracles. I'd rather tell you the truth, because the truth is still genuinely exciting: beginners progress faster than anyone else in the gym. Here's the honest timeline I see over and over with new clients." },
      { h: 'Weeks 1–3: your nervous system wakes up' },
      { p: "Strength jumps quickly at the start — sometimes 5–10% on a lift per week. Almost none of that is new muscle. It's your nervous system learning to coordinate the muscle you already have. Don't be discouraged that the mirror hasn't changed yet; the wiring comes before the hardware." },
      { h: 'Weeks 3–6: the habit locks in' },
      { p: "This is where most people quit — the novelty has worn off and visible change is only starting. It's also exactly where a coach earns their keep. Sessions feel natural, weights keep climbing in small jumps, sleep and appetite usually improve. Around week 5–6, clothes start fitting differently before the scale moves much." },
      { h: 'Weeks 6–12: visible change' },
      { p: "With consistent training and adequate protein, most beginners can build roughly 0.5–1kg of muscle in their first 12 weeks — more for some, less for others, and it varies hugely with sleep, food and genetics. Shoulders and arms usually show first, then the bigger patterns: you look 'trained' rather than just slimmer." },
      { h: 'What actually moves the needle' },
      { p: "Three things, in order: showing up (2–4 sessions a week, every week), progressive overload (small trackable increases — this is why we log everything), and protein (roughly 1.6–2.2g per kg of bodyweight daily). Everything else — supplements, fancy splits, the perfect exercise — is rounding error at this stage." },
      { h: 'The mistake that resets the clock' },
      { p: "Program-hopping. Changing plans every two weeks because something on social media looked better is the fastest way to stay a beginner forever. Pick a sensible program, run it for a full block, then adjust based on data. That's exactly how I run coaching blocks with clients." },
      { p: "General information only — not medical advice. If you have a health condition or injury, talk to your GP or physio before starting a new training program." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'three-day-beginner-split-that-sticks',
    title: 'The 3-day beginner split that actually sticks',
    date: '2026-06-30',
    minutes: 5,
    excerpt: "You don't need a 6-day bro split. Three full-body sessions a week builds more muscle than the perfect program you quit in February.",
    body: [
      { p: "Ask a beginner to train six days a week and you'll get three great weeks followed by silence. Ask them to train three days and you'll still be getting check-in messages in December. Adherence beats optimisation — every single time." },
      { h: 'Why full-body, three days' },
      { p: "As a beginner you don't need much volume to grow — you need frequency and practice. Hitting each movement pattern three times a week means three chances to practise technique, three chances to add a little weight, and no wasted sessions if life eats one of your gym days." },
      { h: 'The template' },
      { p: "Each session: one squat pattern (goblet squat, leg press), one hinge (Romanian deadlift, hip thrust), one push (dumbbell bench, machine press), one pull (lat pulldown, seated row), and one or two accessories you actually enjoy — arms, abs, whatever keeps you coming back. 45–60 minutes, done." },
      { h: 'How to progress it' },
      { p: "The simplest rule in strength training: when you hit the top of the rep range on every set with good form, add the smallest jump available next session. 2.5kg on machines, 1–2kg on dumbbells. Log every session — what gets measured gets built." },
      { h: 'When to change it' },
      { p: "Not after two weeks. Run it for 8–12 weeks, then adjust based on what the log says. If lifts are still climbing, you don't need a new program — you need more weeks of this one. When progress genuinely stalls, that's when block two gets built around your data." },
      { p: "Want this done for you — with the exercises picked for your gym, your schedule and your goals, plus someone checking your form videos? That's my 1:1 coaching. The intro call is free." },
      { p: "General information only — not medical advice. See your GP before starting a new program if you have any health concerns." },
      { p: '— Micah' },
    ],
  },
  {
    slug: 'fat-loss-vs-toning-truth',
    title: "Fat loss vs 'toning up': what's actually happening",
    date: '2026-06-16',
    minutes: 5,
    excerpt: "'I don't want to get bulky, I just want to tone.' Let's clear up the most common confusion in fitness — and why lifting is exactly how you get the look you want.",
    body: [
      { p: "\"I don't want to get big — I just want to tone up.\" I hear this in almost every intro call, usually from someone worried that lifting weights will turn them into a bodybuilder by accident. Here's the reality: 'toned' is just muscle with less fat over it. There is no separate 'toning' exercise. There's building muscle, and there's losing fat, and the look you're after is both." },
      { h: "You can't get bulky by accident" },
      { p: "Building serious size takes years of dedicated training, eating in a surplus, and usually genetics on your side. Nobody wakes up accidentally huge after twelve weeks of goblet squats. What actually happens in your first months of lifting: muscles get a little firmer and rounder, posture improves, and as fat comes off the shape underneath shows through. That IS the toned look." },
      { h: 'Why cardio-only backfires' },
      { p: "Hours of cardio in a big calorie deficit strips muscle along with fat. You end up lighter but softer — 'skinny fat' — and your metabolism takes a hit because you've lost the most metabolically expensive tissue you had. Resistance training while losing fat is what protects the muscle, so what's left behind is shape, not just less of you." },
      { h: 'The actual recipe' },
      { p: "Lift 2–4 times a week with progressive overload. Eat a modest calorie deficit — 300–500 below maintenance, not a starvation diet. Keep protein around 1.6–2.2g per kg of bodyweight. Walk more. Sleep 7+. Run that for 12 weeks and you'll understand why I don't program 'toning circuits' for anyone." },
      { h: 'What the scale won\'t tell you' },
      { p: "When you build muscle while losing fat, the scale can barely move while your body visibly changes. This is why my clients track waist measurements, progress photos and gym numbers — not just weight. More than one client has stayed within 2kg on the scale while dropping two clothing sizes." },
      { p: "General information only — not medical or dietary advice. For personalised nutrition guidance, especially with a medical condition, see a registered dietitian or your GP." },
      { p: '— Micah' },
    ],
  },
]
